---
swagger: "2.0"
info:
  description: "."
  version: "0.1.0"
  title: "Fusion Creator API"
basePath: "/v1"
schemes:
- "http"
- "https"
paths:
  /service:
    get:
      tags:
      - "service"
      summary: "Retrieve the list of services with the description."
      description: "Should include "
      operationId: "listService"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "A list of Services."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceDesc"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Service"
  /application/template:
    get:
      tags:
      - "application template"
      summary: "Retrieve the applications templates"
      description: "Should include "
      operationId: "listApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "A list of Applications."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ApplicationCreation"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "ApplicationTemplate"
  /application:
    get:
      tags:
      - "application"
      summary: "Retrieve the deployed applications"
      description: "Should include "
      operationId: "listApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "A list of Applications."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ApplicationStatus"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
    post:
      tags:
      - "application"
      summary: "Create an application"
      description: "Should include "
      operationId: "createApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "application"
        description: "The application to create."
        required: false
        schema:
          $ref: "#/definitions/ApplicationCreation"
      responses:
        200:
          description: "Application Id."
          schema:
            type: string
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
  /application/{appId}:
    get:
      tags:
      - "application"
      summary: "Get an application."
      description: ""
      operationId: "getApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appId"
        in: "path"
        description: "ID of the app to update"
        required: true
        type: "string"
      responses:
        200:
          description: "An Application."
          schema:
            $ref: "#/definitions/ApplicationStatus"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
    put:
      tags:
      - "application"
      summary: "Update an application"
      description: ""
      operationId: "updateApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appId"
        in: "path"
        description: "ID of the app to update"
        required: true
        type: "string"
      - in: "body"
        name: "application"
        description: "The application to create."
        required: false
        schema:
          $ref: "#/definitions/ApplicationCreation"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
    delete:
      tags:
      - "application"
      summary: "Delete an application"
      description: ""
      operationId: "deleteApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appId"
        in: "path"
        description: "ID of the app to update"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
  /application/{appId}/service:
    get:
      tags:
      - "application"
      summary: "Get the services of an Application"
      description: ""
      operationId: "getAppServices"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appId"
        in: "path"
        description: "ID of the app to update"
        required: true
        type: "string"
      responses:
        200:
          description: "A list of Services."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceStatus"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
    post:
      tags:
      - "application"
      summary: "Add a service"
      description: ""
      operationId: "addServiceApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appId"
        in: "path"
        description: "ID of the app to update"
        required: true
        type: "string"
      - in: "body"
        name: "service"
        description: "The service to add."
        required: false
        schema:
          $ref: "#/definitions/ServiceName"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
  /application/{appId}/service/{serviceId}:
    get:
      tags:
      - "application"
      summary: "Get the deployment status of a service of an application"
      description: ""
      operationId: "getAppServiceStatus"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appId"
        in: "path"
        description: "ID of the app to update"
        required: true
        type: "string"
      - name: "serviceId"
        in: "path"
        description: "ID of the app to update"
        required: true
        type: "string"
      responses:
        200:
          description: "Status of the service."
          schema:
            $ref: "#/definitions/ServiceStatus"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
    delete:
      tags:
      - "application"
      summary: "Delete a service of an application"
      description: ""
      operationId: "deleteAppService"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appId"
        in: "path"
        description: "ID of the app to update"
        required: true
        type: "string"
      - name: "serviceId"
        in: "path"
        description: "ID of the app to update"
        required: true
        type: "string"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
definitions:
  ApplicationCreation:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "string"
        example: "Application id"
      workspace:
        type: "string"
        example: "Traider"  
      name:
        type: "string"
        example: "TrainerTrading"
      services:
        type: "array"
        items:
          $ref: "#/definitions/ServiceName"
  ApplicationStatus:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "string"
        example: "Application id"
      worspace:
        type: "string"
      name:
        type: "string"
        example: "Trainer Trading"
      services:
        type: "array"
        items:
          $ref: "#/definitions/ServiceStatus"
  Service:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "ffdc/reporting"
        description: "The name of the service (required)"
      version:
        type: "string"
        example: "0.1.0"
        description: "A SemVer 2 version"
  ServiceDesc:
    allOf:
    - $ref: "#/definitions/Service"
    - {}
  ServiceStatus:
    allOf:
    - $ref: "#/definitions/Service"
    - {}
  NamedLink:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "reporting"
        description: "The name of the service."
      url:
        type: "string"
        example: "http://reporting"
        description: "Url of the service."
  ServiceName:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "reporting"
        description: "The name of the service."
      version:
        type: "string"
        description: "Version of the service."
