---
swagger: "2.0"
info:
  description: "."
  version: "0.1.0"
  title: "Fusion Creator API"
basePath: "/v1"
schemes:
- "http"
- "https"
paths:
  /service:
    get:
      tags:
      - "service"
      summary: "Retrieve the list of services with the description."
      description: "Should include "
      operationId: "listService"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "A list of Services."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ServiceDesc"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Service"
  /service/{id}:
    delete:
      tags:
      - "service"
      operationId: "deleteService"
      summary: Delete a file.
      consumes:
         - multipart/form-data
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the app to update"
          required: true
          type: "string"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Service"
  /service/repo/{categoryName}/{fileName}:
    get:
      tags:
      - "service"
      operationId: "downloadChart"
      summary: Download a Chart.
      produces: [application/gzip]
      parameters:
        - name: "categoryName"
          in: "path"
          description: "The category to download"
          required: true
          type: "string"
        - name: "fileName"
          in: "path"
          description: "The file to download"
          required: true
          type: "string"
      responses:
        200:
          description: Returns chart
          schema: 
            type: file
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Service"
  /service/repo/index.yaml:
    get:
      tags:
      - "service"
      operationId: "downloadIndex"
      summary: Download a Chart.
      produces: [application/x-yaml]
      responses:
        200:
          description: Returns chart
          schema: 
            type: file
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Service"
  /service/upload/{categoryName}:
    post:
      tags:
      - "service"
      operationId: "uploadService"
      summary: Uploads a Chart.
      consumes:
         - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
          description: The charts to upload.
        - name: "categoryName"
          in: "path"
          description: "Catefory of the chart to push"
          required: true
          type: "string"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Service"
  /application:
    get:
      tags:
      - "application"
      summary: "Retrieve the deployed applications"
      description: "Should include "
      operationId: "listApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "A list of Applications."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ApplicationStatus"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
    post:
      tags:
      - "application"
      summary: "Create an application"
      description: "Should include "
      operationId: "createApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "application"
        description: "The application to create."
        required: false
        schema:
          $ref: "#/definitions/ApplicationCreation"
      responses:
        200:
          description: "Application Id."
          schema:
            type: string
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
  /application/{appId}:
    get:
      tags:
      - "application"
      summary: "Get an application."
      description: ""
      operationId: "getApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "advanced"
        in: "query"
        description: "Advanced mode"
        type: "string"
      - name: "appId"
        in: "path"
        description: "ID of the app to update"
        required: true
        type: "string"
      responses:
        200:
          description: "An Application."
          schema:
            $ref: "#/definitions/ApplicationStatus"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
    delete:
      tags:
      - "application"
      summary: "Delete an application"
      description: ""
      operationId: "deleteApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appId"
        in: "path"
        description: "ID of the app to update"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
  /application/{appId}/service:
    post:
      tags:
      - "application"
      summary: "Add a service"
      description: ""
      operationId: "addServiceApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appId"
        in: "path"
        description: "ID of the app to update"
        required: true
        type: "string"
      - in: "body"
        name: "service"
        description: "The service to add."
        required: false
        schema:
          $ref: "#/definitions/ServiceName"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
  /application/{appId}/service/{serviceId}:
    put:
      tags:
      - "application"
      summary: "Upgrade a service"
      description: ""
      operationId: "upgradeServiceApp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appId"
        in: "path"
        description: "ID of the app to update"
        required: true
        type: "string"
      - name: "serviceId"
        in: "path"
        description: "ID of the service to update"
        required: true
        type: "string"
      - in: "body"
        name: "service"
        description: "The service to add."
        required: false
        schema:
          $ref: "#/definitions/ServiceName"
      responses:
        200:
          description: "Application Id."
          schema:
            type: string
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
  /template:
    get:
      tags:
      - "template"
      summary: "Retrieve the applications templates"
      description: "Should include "
      operationId: "listTemp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "A list of Applications."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ApplicationCreation"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "ApplicationTemplate"
  /application/template:
    post:
      tags:
      - "application"
      summary: "Create an application from a template"
      description: "Should include "
      operationId: "createAppTemplate"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "application"
        description: "The application template to create."
        required: false
        schema:
          $ref: "#/definitions/TemplateName"
      responses:
        200:
          description: "Application Id."
          schema:
            type: string
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Application"
definitions:
  ApplicationCreation:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "string"
        example: "Application id"
      workspace:
        type: "string"
        example: "Traider"  
      name:
        type: "string"
        example: "TrainerTrading"
      services:
        type: "array"
        items:
          $ref: "#/definitions/ServiceName"
  ApplicationStatus:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "string"
        example: "Application id"
      workspace:
        type: "string"
      name:
        type: "string"
        example: "Trainer Trading"
      services:
        type: "array"
        items:
          $ref: "#/definitions/ServiceStatus"
      urls:
        type: "array"
        items:
          $ref: "#/definitions/NamedLink"
  Service:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "ffdc/reporting"
        description: "The name of the service (required)"
      version:
        type: "string"
        example: "0.1.0"
        description: "A SemVer 2 version"
  ServiceDesc:
    allOf:
    - $ref: "#/definitions/Service"
    properties:
      description:
        type: "string"
        example: "reporting"
        description: "The description of the service."
  ServiceStatus:
    allOf:
    - $ref: "#/definitions/Service"
  
  NamedLink:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "reporting"
        description: "The name of the service."
      url:
        type: "string"
        example: "http://reporting"
        description: "Url of the service."
  ServiceName:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "ffdc-raas/reporting"
        description: "The name of the service."
      deployname:
        type: "string"
        example: "reporting"
        description: "The name of the service."
      version:
        type: "string"
        description: "Version of the service."
  TemplateName:
    type: "object"
    required:
    - "templatename"
    - "deployname"
    - "workspace"
    properties:
      templatename:
        type: "string"
        example: "ffdc-raas"
        description: "The name of the template."
      deployname:
        type: "string"
        example: "ffdc-raas"
        description: "The name of the deployment."
      workspace:
        type: "string"
        example: "sample"
        description: "Workspace where the template will be deployed."

